apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: read-db
  name: read-db
spec:
  ports:
  - name: "3307"
    port: 3307
    targetPort: 3307
  selector:
    io.kompose.service: read-db
status:
  loadBalancer: {}
