apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: write-db
  name: write-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: write-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: write-db
    spec:
      containers:
      - args:
        - --default-authentication-plugin=mysql_native_password
        env:
        - name: MYSQL_DATABASE
          value: write_db
        - name: MYSQL_PASSWORD
          value: test
        - name: MYSQL_ROOT_PASSWORD
          value: test
        - name: MYSQL_TCP_PORT
          value: "3308"
        - name: MYSQL_USER
          value: test
        image: mysql:8.0.23
        imagePullPolicy: ""
        name: write-db
        ports:
        - containerPort: 3308
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
