apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: write-db
  name: write-db
spec:
  ports:
  - name: "3308"
    port: 3308
    targetPort: 3308
  selector:
    io.kompose.service: write-db
status:
  loadBalancer: {}
